name: dagger
on:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }

      - name: Build the application
        run: dagger run go run ci/main.go -build=true

      - name: Run the tests
        run: dagger run go run ci/main.go -test=true

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            ./artifacts/zephyr.hex
            ./artifacts/twister_report.xml
          retention-days: 1
